language: node_js
node_js:
  - "7"
script: yarn test
os: linux
dist: trusty
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
before_deploy:
  - yarn run build-website
deploy:
  provider: surge
  project: ./packages/website/build/
  domain: gl-transitions.surge.sh
  skip_cleanup: true
  on:
    branch: master
